- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      register: update_repo

    - name: debug output of update repositories task
      debug:
        var: update_repo.stdout_lines | default('no output generated')

    - name: set default log value
      set_fact:
        playbook_log: "Task logs not available"

  tasks:
    - name: install cron job (ansible-pull)
      cron:
        user: root
        name: ansible-pull
        minute: "*/1"
        job: "ansible-pull -v -U https://github.com/sergioponguta/ansible-pull-smgc"

    - name: Install packages
      apt:
        name:
          - htop
          - mc
          - tmux
          - tree
      register: package_install

    - name: debug output of package installation task
      debug:
        var: package_install.stdout_lines | default('no output generated')

    - name: Capture playbook log output
      debug:
        msg: "TASK: {{ item.name }} | OUTPUT: {{ item.stdout_lines | default('no output generated') }}"
      loop: "{{ ansible_playbook.tasks }}"
      register: task_output

    - name: set playbook log value
      set_fact:
        playbook_log: "{{ task_output.results | map(attribute='msg') | join('\n') }}"

    - name: Send logs to API every time the playbook is run
      uri:
        url: https://aw.globalturing.co/v1/databases/ansible/collections/logs/documents
        method: POST
        body:
          documentId: unique()
          data:
            LOG: "{{ playbook_log }}"
        body_format: json
        headers:
          X-Appwrite-Response-Format: 1.0.0
          X-Appwrite-Project: test
          X-Appwrite-Key: 4aeeed3e470b980750eb934f62a759961b384cf9ea6656f3316211238fccca57b87845a66dc0792993945b25e81c784ac4ed8dc2dcdcf2994bf0566db224d5035d5f1a429e6fcec4d57d61983bd78854293c6dd90043c5fafab3010839bd71317aec904c7dc9d34c5a84a7da23c2d577d221ed1cc66ab492f03c9c66e1e587c5
      register: result
      failed_when: result.status != 201
