# Ansible

- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: false
  tasks:
    - name: install cron job (ansible-pull)
      cron:
        user: root
        name: ansible-pull
        minute: "*/1"
        job: "ansible-pull -v -U https://github.com/sergioponguta/ansible-pull-smgc"
    - name: Install packages
      apt:
        name:
          - htop
          - mc
          - tmux
          - tree
