- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: update repositories
      apt:
        update_cache: yes
      register: output_update_repositories

    - name: install cron job (ansible-pull)
      cron:
        user: root
        name: ansible-pull
        minute: "*/1"
        job: "ansible-pull -v -U https://github.com/sergioponguta/ansible-pull-smgc"
      register: output_install_cron

    - name: Install packages
      apt:
        name:
          - htop
          - mc
          - tmux
          - tree
      register: output_install_packages

    - name: debug output of update repositories task
      debug:
        msg: "update repositories task | {{ output_update_repositories.stdout_lines }}"

    - name: debug output of install cron job task
      debug:
        msg: "install cron job task | {{ output_install_cron.stdout_lines }}"

    - name: debug output of install packages task
      debug:
        msg: "install packages task | {{ output_install_packages.stdout_lines }}"

    - name: Send logs to API every time the playbook is run
      uri:
        url: https://aw.globalturing.co/v1/databases/ansible/collections/logs/documents
        method: POST
        body:
          documentId: unique()
          data:
            LOG: "{% for item in task_output %}{{ item.task_name }} | {{ item.output.stdout_lines }}{% if not loop.last %}\n{% endif %}{% endfor %}"
        body_format: json
        headers:
          X-Appwrite-Response-Format: 1.0.0
          X-Appwrite-Project: test
          X-Appwrite-Key: 4aeeed3e470b980750eb934f62a759961b384cf9ea6656f3316211238fccca57b87845a66dc0792993945b25e81c784ac4ed8dc2dcdcf2994bf0566db224d5035d5f1a429e6fcec4d57d61983bd78854293c6dd90043c5fafab3010839bd71317aec904c7dc9d34c5a84a7da23c2d577d221ed1cc66ab492f03c9c66e1e587c5
      register: result
      failed_when: result.status != 201
      vars:
        task_output:
          - { task_name: "update repositories task", output: "{{ output_update_repositories }}" }
          - { task_name: "install cron job task", output: "{{ output_install_cron }}" }
          - { task_name: "install packages task", output: "{{ output_install_packages }}" }
